ALTER session SET "_ORACLE_SCRIPT" = true;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

SET HEADING OFF
SET FEEDBACK OFF
ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS';
SELECT SYSDATE FROM DUAL
/
SET HEADING ON
SET FEEDBACK ON

CREATE USER spring_db PROFILE DEFAULT
    IDENTIFIED BY spring_db
    DEFAULT TABLESPACE users
    QUOTA UNLIMITED ON users
    TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO spring_db;
GRANT CREATE SEQUENCE TO spring_db;
GRANT CREATE TABLE TO spring_db;
GRANT CREATE VIEW TO spring_db;

