ALTER session SET "_ORACLE_SCRIPT" = true;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

SET HEADING OFF
SET FEEDBACK OFF
ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS';
SELECT SYSDATE FROM DUAL
/
SET HEADING ON
SET FEEDBACK ON

CREATE USER test_spring_db PROFILE DEFAULT
    IDENTIFIED BY test_spring_db
    DEFAULT TABLESPACE users
    QUOTA UNLIMITED ON users
    TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO test_spring_db;
GRANT CREATE SEQUENCE TO test_spring_db;
GRANT CREATE TABLE TO test_spring_db;
GRANT CREATE VIEW TO test_spring_db;

